### ISSUE TITLE
Have mock data routes use baseUri from RAML

### ISSUE THREAD

**Issue by jewelsjacobs** [mulesoft-labs/osprey-mock-service#2]
I would like to see an option to be able to use the baseUri from the RAML as the osprey server with the mock data service's base route as well.  Also accepting any parameters in the baseUri.

For example if your raml is:

``` yaml
#%RAML 0.8
title: Songs REST API
version: v2
baseUri: http://localhost:8081/{version}/{uid}
mediaType:  application/json
baseUriParameters:
  uid:
    description: Unique ID of customer account
    example: 234ghj234ghj
/songs:
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                {"message": "Hey There"}   
```

and the host of your osprey server with the mock data service is `http://localhost:8081` if you pull up
`http://localhost:8081/v2/sf657bhjk6/songs` in your browser you should get the response

``` json
{"message": "Hey There"} 
```

**Comment by blakeembrey** [comment]
@jewelsjacobs Fixed :+1:

**Comment by jewelsjacobs** [comment]
Woohoo! Thanks!
