### ISSUE TITLE
RAML 1.0 support

### ISSUE THREAD

**Issue by acorsinl** [mulesoft-labs/osprey-mock-service#21]
Any idea of when it could be working?

**Comment by blakeembrey** [comment]
When there's a stable parser with consistent output, time to work on it and type system validation. See https://github.com/mulesoft/osprey/issues/81.

**Comment by neilhosey** [comment]
There is a stable parser now :)  Loving this tool, the 1.0 mocking would be great!!  Have yous any idea when this would be available?

**Comment by blakeembrey** [comment]
As I no longer work on the project, you'll need to get an answer from someone at @mulesoft-labs.

**Comment by ashisamazin** [comment]
I would also like 1.0 support please 😄

**Comment by mbonaci** [comment]
Can someone provide some feedback please?

**Comment by jstoiko** [comment]
@mbonaci same as for Osprey, [the RAML 1.0 support PR](https://github.com/mulesoft-labs/osprey-mock-service/pull/24) should be ready to be merged soon. Feel free to give that branch a try as well and let us know if you have any feedback.

**Comment by thevangelist** [comment]
What's the easiest way to try out that branch? I have an existing raml 1.0 project..

**Comment by W1R3D-Code** [comment]
@thevangelist If you've already got the released version installed via npm; checkout the raml1.0 branch, and copy the relevant files into the osprey-mock-service folder in your node_modules folder
i.e. In windows that's %appdata%\npm\node_modules\osprey-mock-service

**Comment by jstoiko** [comment]
@thevangelist: you should also be able to `npm install git+https://github.com/mulesoft-labs/osprey-mock-service.git#raml1.0`

**Comment by yesitspeter** [comment]
I tried the 1.0 branch.  It seems not to work at all with Resource Types.   Any progress or timeline on this?  Just curious.  

` Unknown type <<elementName>> in {"Message" {:name "Message", :displayName "Message", :typePropertyKind "TYPE_EXPRESSION", :type ["object"], :properties {:body {:name "body", :displayName "body", :typePropertyKind "TYPE_EXPRESSION", :type ["string"], :required true, :description "The message content or \"body\""}, :creator {:name "creator", :displayName "creator", :typePropertyKind "TYPE_EXPRESSION", :type ["string"], :required false, :description "The originator of the message"}, :creationTime {:name "creationTime", :displayName "creationTime", :typePropertyKind "TYPE_EXPRESSION", :type ["datetime"], :required false, :description "The time the message was created"}}}, "Messages" {:name "Messages", :displayName "Messages", :typePropertyKind "TYPE_EXPRESSION", :type ["object"], :description "A list of messages", :properties {:messages {:name "messages", :displayName "messages", :typePropertyKind "TYPE_EXPRESSION", :type ["array"], :required true, :items "Message"}}}, "mc.errorTypes.ErrorType" {:name "ErrorType", :displayName "ErrorType", :typePropertyKind "TYPE_EXPRESSION", :type ["object"], :properties {:status {:name "status", :displayName "status", :typePropertyKind "TYPE_EXPRESSION", :type ["integer"], :required false}, :message {:name "message", :displayName "message", :typePropertyKind "TYPE_EXPRESSION", :type ["string"], :required false}, :type {:name "type", :displayName "type", :typePropertyKind "TYPE_EXPRESSION", :type ["string"], :required false}, :moreInfo {:name "moreInfo", :displayName "moreInfo", :typePropertyKind "TYPE_EXPRESSION", :type ["string"], :required false}}}, :path [], :fixpoints #object [cljs.core.Atom {:val {}}]}
    at datatype_expansion$utils$error (C:\Users\peter.okeefe\AppData\Roaming\npm\node_modules\osprey-mock-service\node_modules\datatype-expansion\node\datatype_expansion\utils.js:42:8)
    at datatype_expansion$expanded_form$expanded_form_inner (C:\Users\peter.okeefe\AppData\Roaming\npm\node_modules\osprey-mock-service\node_modules\datatype-expansion\node\datatype_expansion\expanded_form.js:319:39)
    at C:\Users\peter.okeefe\AppData\Roaming\npm\node_modules\osprey-mock-service\node_modules\datatype-expansion\node\datatype_expansion\expanded_form.js:218:61
    at C:\Users\peter.okeefe\AppData\Roaming\npm\node_modules\osprey-mock-service\node_modules\datatype-expansion\node\cljs\core.js:17998:135
    at C:\Users\peter.okeefe\AppData\Roaming\npm\node_modules\osprey-mock-service\node_modules\datatype-expansion\node\cljs\core.js:19036:96
    at C:\Users\peter.okeefe\AppData\Roaming\npm\node_modules\osprey-mock-service\node_modules\datatype-expansion\node\cljs\core.js:19037:3
    at cljs.core.PersistentVector.cljs$core$IReduce$_reduce$arity$3 (C:\Users\peter.okeefe\AppData\Roaming\npm\node_modules\osprey-mock-service\node_modules\datatype-expansion\node\cljs\core.js:19052:3)
    at Function.cljs.core.reduce.cljs$core$IFn$_invoke$arity$3 (C:\Users\peter.okeefe\AppData\Roaming\npm\node_modules\osprey-mock-service\node_modules\datatype-expansion\node\cljs\core.js:7733:13)
    at Function.cljs.core.mapv.cljs$core$IFn$_invoke$arity$2 (C:\Users\peter.okeefe\AppData\Roaming\npm\node_modules\osprey-mock-service\node_modules\datatype-expansion\node\cljs\core.js:17997:52)
    at cljs$core$mapv (C:\Users\peter.okeefe\AppData\Roaming\npm\node_modules\osprey-mock-service\node_modules\datatype-expansion\node\cljs\core.js:17978:23)`

**Comment by jstoiko** [comment]
do you have a RAML file we can look at?

**Comment by yesitspeter** [comment]
Sure.  This was just a test project for a client's sprint 0 activities.  Nothing real.  

[hello_api.zip](https://github.com/mulesoft-labs/osprey-mock-service/files/724771/hello_api.zip)

**Comment by jstoiko** [comment]
This seems to be an issue with [`datatype-expansion`](https://github.com/raml-org/raml-parser-toolbelt/tree/master/tools/datatype-expansion), the library that takes care of library expansion. Let's see what @antoniogarrote thinks.

**Comment by andrew-kratik** [comment]
Hi team!
Do you have updatets on this issue?

**Comment by jstoiko** [comment]
RAML 1.0 is supported since the latest version was released. Some issues related to type expansion have been addressed as well in the most recent patch release. 

closing this issue. feel free to open a new issue if something is still not working.
