### ISSUE TITLE
Support media type extensions

### ISSUE THREAD

**Issue by blakeembrey** [mulesoft-labs/osprey-mock-service#23]
Respond based on `mediaTypeExtension` in RAML 0.8. Need to look at `{ext}` in RAML 1.0.

**Comment by brevity** [comment]
Is it possible to clarify this issue at all?

**Comment by blakeembrey** [comment]
It's been a couple of years, but this issue would be for responding correctly to `{mediaTypeExtension}` from the specification. E.g. https://github.com/raml-apis/AccuWeather/blob/325aceed3f97d4165d8baad596d9945f50aef3a0/accuWeather.raml#L58.
