### ISSUE TITLE
'application/json' type body example content never gets written to the response

### ISSUE THREAD

**Issue by jewelsjacobs** [mulesoft-labs/osprey-mock-service#3]
I can't figure out where these `req.headers.accept` are coming from in

``` javaScript
var type = getType(req.headers.accept, types)
```

https://github.com/mulesoft-labs/osprey-mock-service/blob/master/osprey-mock-service.js#L89

but they always seem to be returning
 `'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'`
even if I add `Accept` headers in the RAML.

This ensures the `'application/json'` type response body will never make it past the condition in the `getType` function resulting in the body example content never getting written to the response despite the HTTP 200 status code.

I also tried messing with the files from https://github.com/raml-org/raml-tutorial-200 and the `'binary/octet-stream'` type in https://github.com/raml-org/raml-tutorial-200/blob/master/jukebox-api.raml#L129 totally hosed this as well.

In general if you want to put the osprey stuff to the test, those files are pretty good because they are kind of nightmarish. :scream:

**Comment by jewelsjacobs** [comment]
If you want to see the RAML / json include files I'm using you can go here:

http://104.130.18.74:8081/ -> API Designer
http://104.130.18.74:8081/documentation/metrics -> Auto Generated Docs from RAML file

The express server file with the osprey server and osprey mock service is [here](https://github.com/jewelsjacobs/raml-osprey-api-designer/blob/master/server.js)

http://104.130.18.74:8081/v2/35436hgvjhgvj/dashboards is supposed to return [this](https://gist.github.com/jewelsjacobs/fdcb7ac98678e7369e78#file-dashboard-data-response-json)

**Comment by jewelsjacobs** [comment]
Oh also forgot to mention if I change
https://github.com/mulesoft-labs/osprey-mock-service/blob/master/osprey-mock-service.js#L140-142
to 

``` javaScript
    if (is.is(contentType, type) || type == 'application/json') {
      return type
    }
```

it works.  Not the jukebox stuff.  When I append `|| type == 'binary/octet-stream'` I get a 404.  I got lost trying to debug that.

**Comment by blakeembrey** [comment]
@jewelsjacobs This is because the browser requests HTML by default. We should only serving JSON responses though. If you make an API request and ask for JSON as the accept type then it'll respond. Same as if you set the type in RAML to `*/*` (theoretically).

**Comment by blakeembrey** [comment]
Now, theoretically, we can respond with the only media type available if you ask for the endpoint and only one exists. Does that make sense?

**Comment by jewelsjacobs** [comment]
Makes total sense! Not sure how you want to validate the body example response though.  Match with an accept header?  Set the default as `'application/json'`?  Set the default as what the RAML object defines as the API media type, ie (in this case `mediaType: application/json`).

``` yaml
#%RAML 0.8

title: Metrics
version: v2
baseUri: http://104.130.18.74:8081/{version}/{uid}
baseUriParameters:
  uid:
    displayName: Unique Account ID
    description: Unique ID of customer account
    example: 35436hgvjhgvj
protocols: [ HTTP, HTTPS ]
mediaType: application/json
```

**Comment by jewelsjacobs** [comment]
So far I've proposed two hacks to allow `'application/json'` body example media type content mock data to be served by a RAML defined endpoint, provided sample code and sample RAML.

What else do you need from me so we can change this module to make this work? :sob:

**Comment by blakeembrey** [comment]
@jewelsjacobs Right now you can make API requests with `Accept: application/json`, but I'm working on fixing this to parse the media type from the browser correctly.

**Comment by blakeembrey** [comment]
@jewelsjacobs I fixed it with proper content type negotiation (https://github.com/mulesoft-labs/osprey-mock-service/commit/07bc01e8f91c028591c41783a4c2c7638a4e5d3b). I just wanted to make sure you understood what was happening and why we don't want to merge "hacks". We want to respond with the appropriate body that the client asks for. If the client asks for `application/json` (`Accept: application/json`) we would respond with `application/json`. Now, we had a pretty bad check there that actually wasn't working on the browser use-case, so I've fixed that and it is working. How it works now (with the browser page) is that it relies on the `*/*` fallback that accepts anything - this will respond with JSON now. Does that make sense? That sort of went everywhere.

Edit: More context. Look at the browser accept header (`text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8`). If you look at a HTTP request that is what the browser sends to a server (by default). It asks for HTML/XML, fallback to an image and finally respond with anything. It's the anything where we want to respond with our JSON.

**Comment by jewelsjacobs** [comment]
I understand hacks are never acceptable and I probably didn't fully understand the situation.  I appreciate your timely fix and explanations!

**Comment by blakeembrey** [comment]
@jewelsjacobs No worried :smile: Make sure it works for you now too (`v0.0.3`), but hopefully the HTTP `Accept` headers make sense.

**Comment by jewelsjacobs** [comment]
YAY! Works like a charm! Also works with that crazy jukebox example.

http://104.130.18.74:8081/

You rock!
