### ISSUE TITLE
Response Header Names are replaced by Numbers

### ISSUE THREAD

**Issue by leflamm** [mulesoft-labs/osprey-mock-service#30]
Existing issue in wrong place I guess: https://github.com/mulesoft/api-designer/issues/472

Header names are replaced by a number, e. g. first header name becomes `0`, second `1` and so on...

```raml
$ cat issue.raml 
#%RAML 1.0
title: issue
version: v1

/foo:
  get:
    responses:
      200:
        headers:
         foo:
           default: 'bar'
           type: string
```

```bash
$ osprey-mock-service -f issue.raml -p 3000
```
`foo: bar` becomes `0: bar`.

```bash
$ curl -v localhost:3000/foo
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /foo HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.50.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< 0: bar
< Date: Fri, 21 Apr 2017 11:14:17 GMT
< Connection: keep-alive
< Content-Length: 0
< 
```

**Comment by jstoiko** [comment]
Thanks for the PR however I'm not sure this is the right repo. AFAIK, api-designer does not use osprey-mock-service.

**Comment by jstoiko** [comment]
This seems to be an issue with the RAML js parser though, so you might want to submit an issue or a PR [there](https://github.com/raml-org/raml-js-parser-2/issues).

**Comment by sichvoge** [comment]
It's probably because it's an array and Osprey is handling them as an object. I think the PR is valid, but it seems that it only handles headers in responses but not in methods.
