### ISSUE TITLE
Response headers returned as `[object Object]`

### ISSUE THREAD

**Issue by goodevilgenius** [mulesoft-labs/osprey-mock-service#40]
Given a raml definition such as:

```yaml
/foo:
  get:
    responses:
      200:
        headers:
          X-Custom-Header:
            description: Describes this header
            example: FooBar
```

I would expect the response to have a header like:

```
X-Custom-Header: FooBar
```

But instead, is returned:

```
X-Custom-Header: [object Object]
```

The error is in the [`setHeaders`](https://github.com/mulesoft-labs/osprey-mock-service/blob/master/osprey-mock-service.js#L144-L147) function. Each header returned by the parser is a complete object, such as:

```json
{
  "name": "X-Custom-Header",
  "displayName": "X-Custom-Header",
  "typePropertyKind": "TYPE_EXPRESSION",
  "type": [
    "string"
  ],
  "example": "FooBar",
  "required": true,
  "description": "Describes this header",
  "structuredExample": {
    "value": "FooBar",
    "strict": true,
    "name": null,
    "structuredValue": "FooBar"
  }
}
```

Therefor, the header should be set from `example`, rather than the header object.

This is with `osprey-mock-service` v0.2.1, `osprey` v0.4.1, and `raml-1-parser` v1.1.39.

**Comment by brevity** [comment]
I know there's a PR for this already, but the issue seems to be fixed on branch develop already.

**Comment by jstoiko** [comment]
This has been addressed and about to be released. Closing this Issue.
