### ISSUE TITLE
Server fails when type returned is boolean

### ISSUE THREAD

**Issue by goodevilgenius** [mulesoft-labs/osprey-mock-service#44]
Suppose I have a route like this:

```yaml
/route:
  get:
    responses:
      200:
        application/json:
          type: boolean
          example: true
```

When I hit that route, the connection is dropped, even though the log shows that 200 was returned.

**Comment by jstoiko** [comment]
Thanks for your PR @goodevilgenius. We're about to release a PATCH so this is timely.
