### ISSUE TITLE
Issue with latest release 0.0.9

### ISSUE THREAD

**Issue by chancharles** [mulesoft-labs/osprey-mock-service#8]
"node" is having problem loading one of the dependencies (osprey). The require("osprey") call returns an empty object.

If we force the dependency on "v0.2.0-beta.1", everything is fine.

**Comment by blakeembrey** [comment]
@chancharles Thanks for the report! I recently pushed an updated API for Osprey and hadn't updated this (actually, I didn't realise the pre-release version would still match). I've just released `0.0.10` with the fix.
